/// A color used by the SGR output encoder
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub enum SgrColor {
    /// Terminal default color
    #[default]
    Default,
    /// Indexed terminal palette entry
    Indexed(u8),
    /// 24-bit RGB color
    Rgb {
        /// Red component
        red: u8,
        /// Green component
        green: u8,
        /// Blue component
        blue: u8,
    },
}

/// A complete terminal SGR style
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct SgrStyle {
    /// Foreground color
    pub foreground: SgrColor,
    /// Background color
    pub background: SgrColor,
    /// Optional underline color
    pub underline_color: Option<SgrColor>,
    /// Bold intensity
    pub bold: bool,
    /// Dim intensity
    pub dim: bool,
    /// Italic text
    pub italic: bool,
    /// Underlined text
    pub underline: bool,
    /// Blinking text
    pub blink: bool,
    /// Reversed foreground and background
    pub reverse: bool,
    /// Hidden text
    pub hidden: bool,
    /// Struck-through text
    pub strikethrough: bool,
}

/// Terminal color encoding level
#[derive(Clone, Copy, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ColorLevel {
    /// Suppress non-default color output
    Monochrome,
    /// Emit only standard and bright ANSI colors
    Ansi16,
    /// Emit indexed 256-color SGR sequences
    #[default]
    Indexed256,
    /// Emit 24-bit RGB SGR sequences
    TrueColor,
}

/// Optional terminal encoder capabilities
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct Capabilities {
    /// Maximum terminal color encoding level
    pub color_level: ColorLevel,
    /// Terminal supports SGR underline color
    pub underline_color: bool,
    /// Terminal supports DECSCUSR cursor shape changes
    pub cursor_shape: bool,
    /// Terminal supports synchronized update mode
    pub synchronized_updates: bool,
}

impl Capabilities {
    /// Safe xterm-compatible baseline with RGB reduced to the indexed palette
    pub const BASELINE: Self = Self {
        color_level: ColorLevel::Indexed256,
        underline_color: false,
        cursor_shape: false,
        synchronized_updates: false,
    };

    /// Modern capabilities used when support has been established
    pub const MODERN: Self = Self {
        color_level: ColorLevel::TrueColor,
        underline_color: true,
        cursor_shape: true,
        synchronized_updates: true,
    };
}

impl Default for Capabilities {
    fn default() -> Self {
        Self::BASELINE
    }
}

/// Erasure range relative to the cursor
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum EraseMode {
    /// From cursor through the end
    After,
    /// From start through the cursor
    Before,
    /// The complete line or display
    All,
}

/// DECSCUSR cursor shape
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum CursorShape {
    /// Terminal default
    Default,
    /// Blinking block
    BlinkingBlock,
    /// Steady block
    SteadyBlock,
    /// Blinking underline
    BlinkingUnderline,
    /// Steady underline
    SteadyUnderline,
    /// Blinking vertical bar
    BlinkingBar,
    /// Steady vertical bar
    SteadyBar,
}

/// Xterm mouse tracking policy
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum MouseTracking {
    /// Button press and release
    Press,
    /// Button events and movement while a button is held
    Button,
    /// All pointer movement
    Any,
}

/// Kitty keyboard protocol progressive-enhancement flags
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct KeyboardEnhancements(u8);

impl KeyboardEnhancements {
    /// No progressive enhancements
    pub const NONE: Self = Self(0);
    /// Report ambiguous modified keys as escape sequences
    pub const DISAMBIGUATE: Self = Self(1);
    /// Report press, repeat, and release actions
    pub const REPORT_EVENT_TYPES: Self = Self(2);
    /// Include shifted and base-layout key alternatives
    pub const REPORT_ALTERNATE_KEYS: Self = Self(4);
    /// Report every key as an escape sequence
    pub const REPORT_ALL_KEYS: Self = Self(8);
    /// Include text generated by a key event
    pub const REPORT_ASSOCIATED_TEXT: Self = Self(16);
    /// Enhancement set used by the standard Nagi terminal runner
    pub const NAGI: Self = Self(
        Self::DISAMBIGUATE.0
            | Self::REPORT_EVENT_TYPES.0
            | Self::REPORT_ALL_KEYS.0
            | Self::REPORT_ASSOCIATED_TEXT.0,
    );

    /// Returns the encoded flag bits
    #[must_use]
    pub const fn bits(self) -> u8 {
        self.0
    }

    /// Returns the union of two enhancement sets
    #[must_use]
    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }

    /// Reports whether every bit in `other` is present
    #[must_use]
    pub const fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
}

/// A pure terminal output operation
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TerminalOp {
    /// Move to a zero-based absolute cell position
    MoveTo {
        /// Zero-based horizontal coordinate
        x: u32,
        /// Zero-based vertical coordinate
        y: u32,
    },
    /// Move by signed cell deltas, vertical before horizontal
    MoveRelative {
        /// Horizontal delta, positive to the right
        dx: i32,
        /// Vertical delta, positive downward
        dy: i32,
    },
    /// Request a one-based cursor position report from the terminal
    RequestCursorPosition,
    /// Request primary device attributes for a capability-query boundary
    RequestPrimaryDeviceAttributes,
    /// Query current Kitty keyboard progressive-enhancement flags
    QueryKeyboardEnhancements,
    /// Push and replace Kitty keyboard progressive-enhancement flags
    PushKeyboardEnhancements(KeyboardEnhancements),
    /// Pop the Kitty keyboard progressive-enhancement stack
    PopKeyboardEnhancements,
    /// Move to column zero of the next line, scrolling when necessary
    NextLine,
    /// Apply a complete SGR style after resetting prior style state
    SetStyle(SgrStyle),
    /// Reset all SGR style state
    ResetStyle,
    /// Write text after replacing terminal control characters with U+FFFD
    WriteText(String),
    /// Erase part or all of the current line
    EraseLine(EraseMode),
    /// Erase part or all of the display
    EraseDisplay(EraseMode),
    /// Show the cursor
    ShowCursor,
    /// Hide the cursor
    HideCursor,
    /// Set the cursor shape when supported
    SetCursorShape(CursorShape),
    /// Enter the alternate screen buffer
    EnterAlternateScreen,
    /// Leave the alternate screen buffer
    LeaveAlternateScreen,
    /// Enable bracketed paste mode
    EnableBracketedPaste,
    /// Disable bracketed paste mode
    DisableBracketedPaste,
    /// Enable SGR mouse reporting
    EnableMouse(MouseTracking),
    /// Disable known mouse reporting modes and SGR encoding
    DisableMouse,
    /// Enable terminal focus reports
    EnableFocus,
    /// Disable terminal focus reports
    DisableFocus,
    /// Set the standard terminal clipboard through write-only OSC 52
    SetClipboard(String),
    /// Begin a synchronized update when supported
    BeginSynchronizedUpdate,
    /// End a synchronized update when supported
    EndSynchronizedUpdate,
}

/// Encodes terminal operations deterministically for `capabilities`
#[must_use]
pub fn encode(operations: &[TerminalOp], capabilities: Capabilities) -> Vec<u8> {
    let mut output = Vec::new();
    append_encoded(&mut output, operations, capabilities);
    output
}

/// Encodes terminal operations after translating absolute positions by an origin
///
/// Relative movement and every non-position operation are unchanged. Coordinate
/// addition saturates at `u32::MAX`.
#[must_use]
pub fn encode_at(
    operations: &[TerminalOp],
    capabilities: Capabilities,
    origin_x: u32,
    origin_y: u32,
) -> Vec<u8> {
    let mut output = Vec::new();
    append_encoded_at(&mut output, operations, capabilities, origin_x, origin_y);
    output
}

/// Appends deterministic terminal encoding to `destination`
pub fn append_encoded(
    destination: &mut Vec<u8>,
    operations: &[TerminalOp],
    capabilities: Capabilities,
) {
    append_encoded_at(destination, operations, capabilities, 0, 0);
}

/// Appends deterministic terminal encoding with an absolute-position origin
///
/// Relative movement and every non-position operation are unchanged. Coordinate
/// addition saturates at `u32::MAX`.
pub fn append_encoded_at(
    destination: &mut Vec<u8>,
    operations: &[TerminalOp],
    capabilities: Capabilities,
    origin_x: u32,
    origin_y: u32,
) {
    for operation in operations {
        encode_operation(destination, operation, capabilities, origin_x, origin_y);
    }
}

fn encode_operation(
    output: &mut Vec<u8>,
    operation: &TerminalOp,
    capabilities: Capabilities,
    origin_x: u32,
    origin_y: u32,
) {
    match operation {
        TerminalOp::MoveTo { x, y } => {
            output.extend_from_slice(b"\x1B[");
            push_decimal(output, u64::from(y.saturating_add(origin_y)) + 1);
            output.push(b';');
            push_decimal(output, u64::from(x.saturating_add(origin_x)) + 1);
            output.push(b'H');
        }
        TerminalOp::MoveRelative { dx, dy } => {
            if *dy < 0 {
                write_csi_count(output, dy.unsigned_abs(), 'A');
            } else if *dy > 0 {
                write_csi_count(output, *dy as u32, 'B');
            }
            if *dx > 0 {
                write_csi_count(output, *dx as u32, 'C');
            } else if *dx < 0 {
                write_csi_count(output, dx.unsigned_abs(), 'D');
            }
        }
        TerminalOp::RequestCursorPosition => output.extend_from_slice(b"\x1B[6n"),
        TerminalOp::RequestPrimaryDeviceAttributes => output.extend_from_slice(b"\x1B[c"),
        TerminalOp::QueryKeyboardEnhancements => output.extend_from_slice(b"\x1B[?u"),
        TerminalOp::PushKeyboardEnhancements(enhancements) => {
            output.extend_from_slice(b"\x1B[>");
            push_decimal(output, u64::from(enhancements.bits()));
            output.push(b'u');
        }
        TerminalOp::PopKeyboardEnhancements => output.extend_from_slice(b"\x1B[<u"),
        TerminalOp::NextLine => output.extend_from_slice(b"\x1BE"),
        TerminalOp::SetStyle(style) => write_style(output, *style, capabilities),
        TerminalOp::ResetStyle => output.extend_from_slice(b"\x1B[0m"),
        TerminalOp::WriteText(text) => write_safe_text(output, text),
        TerminalOp::EraseLine(mode) => write_erase(output, *mode, 'K'),
        TerminalOp::EraseDisplay(mode) => write_erase(output, *mode, 'J'),
        TerminalOp::ShowCursor => output.extend_from_slice(b"\x1B[?25h"),
        TerminalOp::HideCursor => output.extend_from_slice(b"\x1B[?25l"),
        TerminalOp::SetCursorShape(shape) if capabilities.cursor_shape => {
            output.extend_from_slice(b"\x1B[");
            push_decimal(output, u64::from(cursor_shape_code(*shape)));
            output.extend_from_slice(b" q");
        }
        TerminalOp::SetCursorShape(_) => {}
        TerminalOp::EnterAlternateScreen => output.extend_from_slice(b"\x1B[?1049h"),
        TerminalOp::LeaveAlternateScreen => output.extend_from_slice(b"\x1B[?1049l"),
        TerminalOp::EnableBracketedPaste => output.extend_from_slice(b"\x1B[?2004h"),
        TerminalOp::DisableBracketedPaste => output.extend_from_slice(b"\x1B[?2004l"),
        TerminalOp::EnableMouse(tracking) => {
            let mode = match tracking {
                MouseTracking::Press => 1000,
                MouseTracking::Button => 1002,
                MouseTracking::Any => 1003,
            };
            output.extend_from_slice(b"\x1B[?");
            push_decimal(output, mode);
            output.extend_from_slice(b"h\x1B[?1006h");
        }
        TerminalOp::DisableMouse => {
            output.extend_from_slice(b"\x1B[?1000l\x1B[?1002l\x1B[?1003l\x1B[?1006l");
        }
        TerminalOp::EnableFocus => output.extend_from_slice(b"\x1B[?1004h"),
        TerminalOp::DisableFocus => output.extend_from_slice(b"\x1B[?1004l"),
        TerminalOp::SetClipboard(text) => write_clipboard(output, text),
        TerminalOp::BeginSynchronizedUpdate if capabilities.synchronized_updates => {
            output.extend_from_slice(b"\x1B[?2026h");
        }
        TerminalOp::EndSynchronizedUpdate if capabilities.synchronized_updates => {
            output.extend_from_slice(b"\x1B[?2026l");
        }
        TerminalOp::BeginSynchronizedUpdate | TerminalOp::EndSynchronizedUpdate => {}
    }
}

fn write_clipboard(output: &mut Vec<u8>, text: &str) {
    output.extend_from_slice(b"\x1B]52;c;");
    write_base64(output, text.as_bytes());
    output.extend_from_slice(b"\x1B\\");
}

fn write_base64(output: &mut Vec<u8>, input: &[u8]) {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut chunks = input.chunks_exact(3);
    for chunk in &mut chunks {
        output.push(ALPHABET[usize::from(chunk[0] >> 2)]);
        output.push(ALPHABET[usize::from((chunk[0] & 0x03) << 4 | chunk[1] >> 4)]);
        output.push(ALPHABET[usize::from((chunk[1] & 0x0F) << 2 | chunk[2] >> 6)]);
        output.push(ALPHABET[usize::from(chunk[2] & 0x3F)]);
    }
    match chunks.remainder() {
        [first] => {
            output.push(ALPHABET[usize::from(first >> 2)]);
            output.push(ALPHABET[usize::from((first & 0x03) << 4)]);
            output.extend_from_slice(b"==");
        }
        [first, second] => {
            output.push(ALPHABET[usize::from(first >> 2)]);
            output.push(ALPHABET[usize::from((first & 0x03) << 4 | second >> 4)]);
            output.push(ALPHABET[usize::from((second & 0x0F) << 2)]);
            output.push(b'=');
        }
        [] => {}
        _ => unreachable!("chunks_exact remainder is shorter than three bytes"),
    }
}

fn write_csi_count(output: &mut Vec<u8>, count: u32, final_character: char) {
    output.extend_from_slice(b"\x1B[");
    push_decimal(output, u64::from(count));
    output.push(final_character as u8);
}

fn write_erase(output: &mut Vec<u8>, mode: EraseMode, final_character: char) {
    let parameter = match mode {
        EraseMode::After => 0,
        EraseMode::Before => 1,
        EraseMode::All => 2,
    };
    output.extend_from_slice(b"\x1B[");
    output.push(b'0' + parameter);
    output.push(final_character as u8);
}

fn cursor_shape_code(shape: CursorShape) -> u8 {
    match shape {
        CursorShape::Default => 0,
        CursorShape::BlinkingBlock => 1,
        CursorShape::SteadyBlock => 2,
        CursorShape::BlinkingUnderline => 3,
        CursorShape::SteadyUnderline => 4,
        CursorShape::BlinkingBar => 5,
        CursorShape::SteadyBar => 6,
    }
}

fn write_style(output: &mut Vec<u8>, style: SgrStyle, capabilities: Capabilities) {
    output.extend_from_slice(b"\x1B[0");
    push_color(output, style.foreground, true, capabilities);
    push_color(output, style.background, false, capabilities);
    if capabilities.underline_color && capabilities.color_level >= ColorLevel::Indexed256 {
        if let Some(color) = style.underline_color {
            push_extended_color(output, color, 58, capabilities);
        }
    }
    let attributes = [
        (style.bold, 1),
        (style.dim, 2),
        (style.italic, 3),
        (style.underline, 4),
        (style.blink, 5),
        (style.reverse, 7),
        (style.hidden, 8),
        (style.strikethrough, 9),
    ];
    for (enabled, code) in attributes {
        if enabled {
            push_parameter(output, code);
        }
    }
    output.push(b'm');
}

fn push_color(output: &mut Vec<u8>, color: SgrColor, foreground: bool, capabilities: Capabilities) {
    if color == SgrColor::Default || capabilities.color_level == ColorLevel::Monochrome {
        return;
    }
    push_extended_color(
        output,
        color,
        if foreground { 38 } else { 48 },
        capabilities,
    );
}

fn push_extended_color(
    output: &mut Vec<u8>,
    color: SgrColor,
    prefix: u8,
    capabilities: Capabilities,
) {
    match color {
        SgrColor::Default => push_parameter(
            output,
            match prefix {
                48 => 49,
                58 => 59,
                _ => 39,
            },
        ),
        SgrColor::Indexed(index) if capabilities.color_level >= ColorLevel::Indexed256 => {
            push_indexed_color(output, prefix, index);
        }
        SgrColor::Indexed(index) => push_ansi16_color(output, prefix, index_to_ansi16(index)),
        SgrColor::Rgb { red, green, blue } if capabilities.color_level == ColorLevel::TrueColor => {
            push_parameter(output, u64::from(prefix));
            push_parameter(output, 2);
            push_parameter(output, u64::from(red));
            push_parameter(output, u64::from(green));
            push_parameter(output, u64::from(blue));
        }
        SgrColor::Rgb { red, green, blue }
            if capabilities.color_level == ColorLevel::Indexed256 =>
        {
            push_indexed_color(output, prefix, indexed_rgb(red, green, blue));
        }
        SgrColor::Rgb { red, green, blue } => {
            push_ansi16_color(output, prefix, rgb_to_ansi16(red, green, blue));
        }
    }
}

fn push_indexed_color(output: &mut Vec<u8>, prefix: u8, index: u8) {
    push_parameter(output, u64::from(prefix));
    push_parameter(output, 5);
    push_parameter(output, u64::from(index));
}

fn push_ansi16_color(output: &mut Vec<u8>, prefix: u8, index: u8) {
    let bright = index >= 8;
    let base = match (prefix, bright) {
        (48, false) => 40,
        (48, true) => 100,
        (_, false) => 30,
        (_, true) => 90,
    };
    push_parameter(output, u64::from(base + index % 8));
}

fn index_to_ansi16(index: u8) -> u8 {
    match index {
        0..=15 => index,
        16..=231 => {
            let cube = index - 16;
            cube_to_ansi16(cube / 36, cube / 6 % 6, cube % 6)
        }
        232..=243 => 0,
        244..=255 => 15,
    }
}

fn rgb_to_ansi16(red: u8, green: u8, blue: u8) -> u8 {
    cube_to_ansi16(
        u8::from(red >= 128) * 5,
        u8::from(green >= 128) * 5,
        u8::from(blue >= 128) * 5,
    )
}

fn cube_to_ansi16(red: u8, green: u8, blue: u8) -> u8 {
    let bits = u8::from(red >= 3) + 2 * u8::from(green >= 3) + 4 * u8::from(blue >= 3);
    let bright = red.max(green).max(blue) >= 5;
    bits + 8 * u8::from(bright)
}

fn indexed_rgb(red: u8, green: u8, blue: u8) -> u8 {
    let level = |component: u8| ((u16::from(component) * 5 + 127) / 255) as u8;
    16 + 36 * level(red) + 6 * level(green) + level(blue)
}

fn write_safe_text(output: &mut Vec<u8>, text: &str) {
    for character in text.chars() {
        let character = if matches!(u32::from(character), 0x00..=0x1F | 0x7F..=0x9F) {
            '\u{FFFD}'
        } else {
            character
        };
        let mut buffer = [0; 4];
        output.extend_from_slice(character.encode_utf8(&mut buffer).as_bytes());
    }
}

fn push_parameter(output: &mut Vec<u8>, value: u64) {
    output.push(b';');
    push_decimal(output, value);
}

fn push_decimal(output: &mut Vec<u8>, mut value: u64) {
    let mut buffer = [0_u8; 20];
    let mut start = buffer.len();
    loop {
        start -= 1;
        buffer[start] = b'0' + (value % 10) as u8;
        value /= 10;
        if value == 0 {
            break;
        }
    }
    output.extend_from_slice(&buffer[start..]);
}

#[cfg(test)]
mod tests {
    use super::{Capabilities, TerminalOp, append_encoded, encode, encode_at};

    #[test]
    fn text_cannot_inject_terminal_controls() {
        assert_eq!(
            encode(
                &[TerminalOp::WriteText("a\x1B[31m".to_owned())],
                Capabilities::MODERN,
            ),
            "a\u{FFFD}[31m".as_bytes()
        );
    }

    #[test]
    fn minimum_relative_delta_does_not_overflow() {
        assert_eq!(
            encode(
                &[TerminalOp::MoveRelative {
                    dx: i32::MIN,
                    dy: i32::MIN,
                }],
                Capabilities::BASELINE,
            ),
            b"\x1B[2147483648A\x1B[2147483648D"
        );
    }

    #[test]
    fn append_encoded_preserves_destination_prefix() {
        let mut output = b"prefix:".to_vec();
        append_encoded(
            &mut output,
            &[
                TerminalOp::MoveTo { x: 2, y: 3 },
                TerminalOp::WriteText("ok".to_owned()),
            ],
            Capabilities::BASELINE,
        );
        assert_eq!(output, b"prefix:\x1B[4;3Hok");
    }

    #[test]
    fn origin_only_translates_absolute_positions_and_saturates() {
        assert_eq!(
            encode_at(
                &[
                    TerminalOp::MoveTo { x: 2, y: 3 },
                    TerminalOp::MoveRelative { dx: 1, dy: -1 },
                    TerminalOp::MoveTo {
                        x: u32::MAX,
                        y: u32::MAX,
                    },
                ],
                Capabilities::BASELINE,
                5,
                7,
            ),
            b"\x1B[11;8H\x1B[1A\x1B[1C\x1B[4294967296;4294967296H"
        );
    }

    #[test]
    fn clipboard_uses_base64_without_exposing_raw_controls() {
        assert_eq!(
            encode(
                &[TerminalOp::SetClipboard("a\x1B日".to_owned())],
                Capabilities::BASELINE,
            ),
            b"\x1B]52;c;YRvml6U=\x1B\\"
        );
    }
}
