[package]
name = "nagi-cli-document"
description = "Markdown and man page Help renderers for Nagi CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[lints.rust]
missing_docs = "deny"
unsafe_code = "allow"

[dependencies]
nagi-cli = { path = "../nagi-cli", version = "0.2.7" }

[[bench]]
name = "document"
harness = false
