use std::ffi::{c_int, c_short, c_ulong, c_void};
use std::io;
use std::mem::MaybeUninit;
use std::sync::atomic::{AtomicBool, AtomicI32, AtomicUsize, Ordering};
use std::time::Duration;

use super::session::{Backend, WaitReady};

#[cfg(not(any(
    all(
        target_os = "linux",
        any(target_arch = "x86_64", target_arch = "aarch64")
    ),
    all(
        target_os = "macos",
        any(target_arch = "x86_64", target_arch = "aarch64")
    ),
)))]
compile_error!("Nagi TUI terminal integration supports Linux and macOS on x86_64 and aarch64");

const TCSANOW: c_int = 0;
const POLLIN: c_short = 0x0001;
const POLLERR: c_short = 0x0008;
const POLLHUP: c_short = 0x0010;
const POLLNVAL: c_short = 0x0020;
const SIGWINCH: c_int = 28;
const SIG_ERR: usize = usize::MAX;

#[cfg(target_os = "linux")]
const TIOCGWINSZ: c_ulong = 0x5413;
#[cfg(target_os = "macos")]
const TIOCGWINSZ: c_ulong = 0x4008_7468;

// Layout source: glibc bits/termios-struct.h as generated by Go's syscall
// package for linux/amd64 and linux/arm64.
#[cfg(target_os = "linux")]
#[derive(Clone)]
#[repr(C)]
pub(crate) struct Termios {
    input_flags: u32,
    output_flags: u32,
    control_flags: u32,
    local_flags: u32,
    line: u8,
    control_characters: [u8; 32],
    input_speed: u32,
    output_speed: u32,
}

// Layout source: the macOS SDK sys/termios.h. The implicit padding after
// control_characters aligns the two unsigned-long speed fields.
#[cfg(target_os = "macos")]
#[derive(Clone)]
#[repr(C)]
pub(crate) struct Termios {
    input_flags: u64,
    output_flags: u64,
    control_flags: u64,
    local_flags: u64,
    control_characters: [u8; 20],
    input_speed: u64,
    output_speed: u64,
}

#[repr(C)]
struct PollFd {
    fd: c_int,
    events: c_short,
    revents: c_short,
}

#[repr(C)]
struct WindowSize {
    rows: u16,
    columns: u16,
    x_pixels: u16,
    y_pixels: u16,
}

#[cfg(target_os = "linux")]
type Nfds = c_ulong;
#[cfg(target_os = "macos")]
type Nfds = u32;

unsafe extern "C" {
    fn tcgetattr(fd: c_int, state: *mut Termios) -> c_int;
    fn tcsetattr(fd: c_int, action: c_int, state: *const Termios) -> c_int;
    fn cfmakeraw(state: *mut Termios);
    fn ioctl(fd: c_int, request: c_ulong, ...) -> c_int;
    fn poll(descriptors: *mut PollFd, count: Nfds, timeout_ms: c_int) -> c_int;
    fn read(fd: c_int, buffer: *mut c_void, count: usize) -> isize;
    fn write(fd: c_int, buffer: *const c_void, count: usize) -> isize;
    fn signal(signal: c_int, handler: usize) -> usize;
}

static RESIZE_PENDING: AtomicBool = AtomicBool::new(false);
static RESIZE_HANDLER_OWNED: AtomicBool = AtomicBool::new(false);
static RESIZE_WAKE_FD: AtomicI32 = AtomicI32::new(-1);
static RESIZE_HANDLER_ACTIVE: AtomicUsize = AtomicUsize::new(0);

extern "C" fn mark_resize_pending(_signal: c_int) {
    RESIZE_HANDLER_ACTIVE.fetch_add(1, Ordering::AcqRel);
    RESIZE_PENDING.store(true, Ordering::Relaxed);
    let fd = RESIZE_WAKE_FD.load(Ordering::Acquire);
    if fd >= 0 {
        let byte = [1_u8];
        // SAFETY: write is async-signal-safe and byte remains valid for the
        // call. Restoration waits for active handlers before closing the
        // descriptor.
        unsafe {
            write(fd, byte.as_ptr().cast(), byte.len());
        }
    }
    RESIZE_HANDLER_ACTIVE.fetch_sub(1, Ordering::Release);
}

pub(crate) struct UnixBackend;

pub(crate) struct SignalGuard {
    previous_handler: usize,
}

impl Backend for UnixBackend {
    type SignalGuard = SignalGuard;
    type State = Termios;

    fn get_state(&mut self, fd: i32) -> io::Result<Self::State> {
        let mut state = MaybeUninit::uninit();
        // SAFETY: state points to writable storage with the platform termios
        // layout, and tcgetattr initializes it completely on success.
        let result = unsafe { tcgetattr(fd, state.as_mut_ptr()) };
        if result == -1 {
            Err(io::Error::last_os_error())
        } else {
            // SAFETY: tcgetattr returned success and initialized state.
            Ok(unsafe { state.assume_init() })
        }
    }

    fn make_raw(&mut self, state: &mut Self::State) {
        // SAFETY: state is a valid platform termios value obtained from
        // tcgetattr. cfmakeraw only mutates fields in that value.
        unsafe { cfmakeraw(state) };
    }

    fn set_state(&mut self, fd: i32, state: &Self::State) -> io::Result<()> {
        // SAFETY: state has the platform termios layout and remains valid for
        // the duration of the call. TCSANOW is valid on Linux and macOS.
        let result = unsafe { tcsetattr(fd, TCSANOW, state) };
        cvt(result).map(|_| ())
    }

    fn install_resize_handler(&mut self, wake_fd: i32) -> io::Result<Self::SignalGuard> {
        if RESIZE_HANDLER_OWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                "a Nagi TUI terminal session is already active",
            ));
        }
        RESIZE_PENDING.store(true, Ordering::Release);
        RESIZE_WAKE_FD.store(wake_fd, Ordering::Release);
        // SAFETY: signal uses the C ABI and mark_resize_pending has the
        // required handler signature. The handler only performs lock-free
        // atomic operations and an async-signal-safe write.
        let previous_handler =
            unsafe { signal(SIGWINCH, mark_resize_pending as *const () as usize) };
        if previous_handler == SIG_ERR {
            RESIZE_WAKE_FD.store(-1, Ordering::Release);
            RESIZE_HANDLER_OWNED.store(false, Ordering::Release);
            return Err(io::Error::last_os_error());
        }
        Ok(SignalGuard { previous_handler })
    }

    fn restore_resize_handler(&mut self, guard: Self::SignalGuard) -> io::Result<()> {
        RESIZE_WAKE_FD.store(-1, Ordering::Release);
        // SAFETY: previous_handler is the value returned by the successful
        // signal call paired with this guard.
        let result = unsafe { signal(SIGWINCH, guard.previous_handler) };
        while RESIZE_HANDLER_ACTIVE.load(Ordering::Acquire) != 0 {
            std::hint::spin_loop();
        }
        RESIZE_HANDLER_OWNED.store(false, Ordering::Release);
        if result == SIG_ERR {
            Err(io::Error::last_os_error())
        } else {
            Ok(())
        }
    }

    fn resize_pending(&mut self) -> bool {
        RESIZE_PENDING.swap(false, Ordering::AcqRel)
    }

    fn read(&mut self, fd: i32, buffer: &mut [u8]) -> io::Result<usize> {
        // SAFETY: buffer supplies writable storage for exactly buffer.len()
        // bytes and remains borrowed for the duration of read.
        let result = unsafe { read(fd, buffer.as_mut_ptr().cast(), buffer.len()) };
        cvt_size(result)
    }

    fn write(&mut self, fd: i32, buffer: &[u8]) -> io::Result<usize> {
        // SAFETY: buffer supplies readable storage for exactly buffer.len()
        // bytes and remains borrowed for the duration of write.
        let result = unsafe { write(fd, buffer.as_ptr().cast(), buffer.len()) };
        cvt_size(result)
    }

    fn wait(
        &mut self,
        input_fd: i32,
        wake_fd: i32,
        timeout: Option<Duration>,
    ) -> io::Result<WaitReady> {
        let mut descriptors = [
            PollFd {
                fd: input_fd,
                events: POLLIN,
                revents: 0,
            },
            PollFd {
                fd: wake_fd,
                events: POLLIN,
                revents: 0,
            },
        ];
        let timeout_ms = timeout.map_or(-1, timeout_milliseconds);
        // SAFETY: descriptors points to two initialized pollfd values and
        // timeout_ms is either the infinite sentinel or a nonnegative C int.
        let result = unsafe { poll(descriptors.as_mut_ptr(), 2, timeout_ms) };
        if result == -1 {
            let error = io::Error::last_os_error();
            if error.kind() == io::ErrorKind::Interrupted {
                return Ok(WaitReady::default());
            }
            return Err(error);
        }
        if result == 0 {
            return Ok(WaitReady::default());
        }
        for descriptor in &descriptors {
            if descriptor.revents & POLLNVAL != 0 {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "poll rejected a terminal event descriptor",
                ));
            }
            if descriptor.revents & POLLERR != 0 {
                return Err(io::Error::other(
                    "terminal event descriptor reported a poll error",
                ));
            }
        }
        Ok(WaitReady {
            input: descriptors[0].revents & (POLLIN | POLLHUP) != 0,
            wake: descriptors[1].revents & (POLLIN | POLLHUP) != 0,
        })
    }

    fn size(&mut self, fd: i32) -> io::Result<(u16, u16)> {
        let mut size = WindowSize {
            rows: 0,
            columns: 0,
            x_pixels: 0,
            y_pixels: 0,
        };
        // SAFETY: size is writable storage with the winsize layout shared by
        // Linux and macOS, and TIOCGWINSZ writes that structure.
        let result = unsafe { ioctl(fd, TIOCGWINSZ, &mut size as *mut WindowSize) };
        cvt(result)?;
        if size.columns == 0 || size.rows == 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "terminal reported a zero-sized window",
            ));
        }
        Ok((size.columns, size.rows))
    }
}

fn timeout_milliseconds(timeout: Duration) -> c_int {
    timeout
        .as_millis()
        .saturating_add(u128::from(timeout.subsec_nanos() % 1_000_000 != 0))
        .min(c_int::MAX as u128) as c_int
}

fn cvt(result: c_int) -> io::Result<c_int> {
    if result == -1 {
        Err(io::Error::last_os_error())
    } else {
        Ok(result)
    }
}

fn cvt_size(result: isize) -> io::Result<usize> {
    if result == -1 {
        Err(io::Error::last_os_error())
    } else {
        Ok(result as usize)
    }
}

#[cfg(test)]
mod tests {
    use std::mem::{align_of, size_of};
    use std::sync::mpsc;
    use std::thread;

    use super::*;
    use crate::terminal_unix::wake::WakePipe;
    use crate::wake::RuntimeWake;

    #[test]
    fn abi_layouts_match_supported_platform_headers() {
        assert_eq!(size_of::<PollFd>(), 8);
        assert_eq!(size_of::<WindowSize>(), 8);
        #[cfg(target_os = "linux")]
        {
            assert_eq!(align_of::<Termios>(), 4);
            assert_eq!(size_of::<Termios>(), 60);
        }
        #[cfg(target_os = "macos")]
        {
            assert_eq!(align_of::<Termios>(), 8);
            assert_eq!(size_of::<Termios>(), 72);
        }
    }

    #[test]
    fn timeout_rounding_contract_covers_sub_millisecond_waits() {
        let timeout = Duration::from_nanos(1);
        assert_eq!(timeout_milliseconds(timeout), 1);
    }

    #[test]
    fn wait_without_deadline_returns_for_runtime_wake() {
        let input = WakePipe::new().unwrap();
        let wake = WakePipe::new().unwrap();
        let input_fd = input.read_fd();
        let wake_fd = wake.read_fd();
        let (started_sender, started_receiver) = mpsc::channel();
        let (result_sender, result_receiver) = mpsc::channel();

        let worker = thread::spawn(move || {
            let _ = started_sender.send(());
            let result = UnixBackend.wait(input_fd, wake_fd, None);
            let _ = result_sender.send(result);
        });
        started_receiver.recv().unwrap();
        RuntimeWake::notify(wake.as_ref());

        let ready = result_receiver
            .recv_timeout(Duration::from_secs(1))
            .expect("wait did not return for runtime wake-up")
            .unwrap();
        assert_eq!(
            ready,
            WaitReady {
                input: false,
                wake: true
            }
        );
        worker.join().unwrap();
    }
}
