use std::fs::File;
use std::io::{self, IsTerminal, Read, Write};
use std::os::fd::{AsRawFd, RawFd};

use nagi_cli::CancellationToken;

use crate::{InputMode, PromptIo, ReadResult};

#[cfg(not(any(
    all(
        target_os = "linux",
        any(target_arch = "x86_64", target_arch = "aarch64")
    ),
    all(
        target_os = "macos",
        any(target_arch = "x86_64", target_arch = "aarch64")
    ),
)))]
compile_error!("Nagi CLI Prompt process I/O supports Linux and macOS on x86_64 and aarch64");

const WAIT_MILLISECONDS: i32 = 100;
const TCSANOW: std::ffi::c_int = 0;
const ECHO: LocalFlags = 0x0000_0008;
#[cfg(target_os = "linux")]
const ECHONL: LocalFlags = 0x0000_0040;
#[cfg(target_os = "macos")]
const ECHONL: LocalFlags = 0x0000_0010;
const POLLIN: std::ffi::c_short = 0x0001;

#[cfg(target_os = "linux")]
type LocalFlags = u32;
#[cfg(target_os = "macos")]
type LocalFlags = u64;

#[cfg(target_os = "linux")]
// Layout source: glibc bits/termios-struct.h as generated by Go's syscall
// package for Linux on x86-64 and ARM64
#[derive(Clone, Debug, Eq, PartialEq)]
#[repr(C)]
struct Termios {
    input_flags: u32,
    output_flags: u32,
    control_flags: u32,
    local_flags: u32,
    line: u8,
    control_characters: [u8; 32],
    input_speed: u32,
    output_speed: u32,
}

#[cfg(target_os = "macos")]
// Layout source: the macOS SDK sys/termios.h. Implicit padding after the
// control-character array aligns the unsigned-long speed fields
#[derive(Clone, Debug, Eq, PartialEq)]
#[repr(C)]
struct Termios {
    input_flags: u64,
    output_flags: u64,
    control_flags: u64,
    local_flags: u64,
    control_characters: [u8; 20],
    input_speed: u64,
    output_speed: u64,
}

#[repr(C)]
struct PollFd {
    fd: std::ffi::c_int,
    events: std::ffi::c_short,
    revents: std::ffi::c_short,
}

#[cfg(target_os = "linux")]
type Nfds = std::ffi::c_ulong;
#[cfg(target_os = "macos")]
type Nfds = u32;

unsafe extern "C" {
    fn tcgetattr(fd: std::ffi::c_int, state: *mut Termios) -> std::ffi::c_int;
    fn tcsetattr(
        fd: std::ffi::c_int,
        action: std::ffi::c_int,
        state: *const Termios,
    ) -> std::ffi::c_int;
    fn poll(descriptors: *mut PollFd, count: Nfds, timeout_ms: i32) -> std::ffi::c_int;
}

trait InputFile: Read + AsRawFd + IsTerminal {}
impl<T: Read + AsRawFd + IsTerminal> InputFile for T {}

trait OutputFile: Write + AsRawFd + IsTerminal {}
impl<T: Write + AsRawFd + IsTerminal> OutputFile for T {}

/// Unix process prompt I/O backed by standard input and standard error
pub struct ProcessIo {
    input: Box<dyn InputFile>,
    output: Box<dyn OutputFile>,
    buffer: [u8; 4_096],
    start: usize,
    end: usize,
    eof: bool,
}

impl ProcessIo {
    /// Constructs process I/O from owned files
    ///
    /// This is useful when an application opens `/dev/tty` explicitly. The
    /// ordinary [`Default`] implementation uses standard input and error
    pub fn new(input: File, output: File) -> Self {
        Self::from_streams(input, output)
    }

    fn from_streams(input: impl InputFile + 'static, output: impl OutputFile + 'static) -> Self {
        Self {
            input: Box::new(input),
            output: Box::new(output),
            buffer: [0; 4_096],
            start: 0,
            end: 0,
            eof: false,
        }
    }

    fn read_bounded_line(
        &mut self,
        cancellation: &CancellationToken,
        max_bytes: usize,
    ) -> io::Result<ReadResult> {
        let mut line = Vec::with_capacity(max_bytes.min(1_024));
        let mut discarded = false;
        loop {
            while self.start < self.end {
                let byte = self.buffer[self.start];
                self.start += 1;
                if byte == b'\n' {
                    if line.last() == Some(&b'\r') {
                        line.pop();
                    }
                    return if discarded || line.len() > max_bytes {
                        Ok(ReadResult::InputTooLong)
                    } else {
                        Ok(ReadResult::Line(line))
                    };
                }
                if line.len() <= max_bytes {
                    line.push(byte);
                } else {
                    discarded = true;
                }
            }
            self.start = 0;
            self.end = 0;
            if self.eof {
                return if line.is_empty() && !discarded {
                    Ok(ReadResult::EndOfFile)
                } else if discarded || line.len() > max_bytes {
                    Ok(ReadResult::InputTooLong)
                } else {
                    Ok(ReadResult::Line(line))
                };
            }
            if cancellation.is_cancelled() {
                return Ok(ReadResult::Cancelled);
            }
            if !wait_readable(self.input.as_raw_fd())? {
                continue;
            }
            match self.input.read(&mut self.buffer) {
                Ok(0) => self.eof = true,
                Ok(count) => self.end = count,
                Err(error) if error.kind() == io::ErrorKind::Interrupted => continue,
                Err(error) => return Err(error),
            }
        }
    }
}

impl Default for ProcessIo {
    fn default() -> Self {
        Self::from_streams(io::stdin(), io::stderr())
    }
}

impl Write for ProcessIo {
    fn write(&mut self, buffer: &[u8]) -> io::Result<usize> {
        self.output.write(buffer)
    }

    fn flush(&mut self) -> io::Result<()> {
        self.output.flush()
    }
}

impl PromptIo for ProcessIo {
    fn is_terminal(&self) -> bool {
        self.input.is_terminal() && self.output.is_terminal()
    }

    fn read_line(
        &mut self,
        cancellation: &CancellationToken,
        mode: InputMode,
        max_bytes: usize,
    ) -> io::Result<ReadResult> {
        if max_bytes == 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "prompt input limit must be non-zero",
            ));
        }
        if mode == InputMode::Visible {
            return self.read_bounded_line(cancellation, max_bytes);
        }
        let mut restore = EchoRestore::disable(self.input.as_raw_fd())?;
        let result = self.read_bounded_line(cancellation, max_bytes);
        let restore_result = restore.restore();
        match (result, restore_result) {
            (_, Err(error)) => Err(error),
            (result, Ok(())) => result,
        }
    }
}

struct EchoRestore {
    fd: RawFd,
    original: Option<Termios>,
}

impl EchoRestore {
    fn disable(fd: RawFd) -> io::Result<Self> {
        let original = terminal_state(fd)?;
        let mut hidden = original.clone();
        hidden.local_flags &= !(ECHO | ECHONL);
        set_terminal_state(fd, &hidden)?;
        Ok(Self {
            fd,
            original: Some(original),
        })
    }

    fn restore(&mut self) -> io::Result<()> {
        let Some(original) = self.original.take() else {
            return Ok(());
        };
        set_terminal_state(self.fd, &original)
    }
}

impl Drop for EchoRestore {
    fn drop(&mut self) {
        let _ = self.restore();
    }
}

fn terminal_state(fd: RawFd) -> io::Result<Termios> {
    loop {
        let mut state = std::mem::MaybeUninit::uninit();
        // SAFETY: state points to writable storage with the platform termios
        // layout and tcgetattr initializes it completely on success
        let result = unsafe { tcgetattr(fd, state.as_mut_ptr()) };
        if result != -1 {
            // SAFETY: tcgetattr returned success and initialized the value
            return Ok(unsafe { state.assume_init() });
        }
        let error = io::Error::last_os_error();
        if error.kind() != io::ErrorKind::Interrupted {
            return Err(error);
        }
    }
}

fn set_terminal_state(fd: RawFd, state: &Termios) -> io::Result<()> {
    loop {
        // SAFETY: state was derived from tcgetattr and remains valid for the
        // call
        let result = unsafe { tcsetattr(fd, TCSANOW, state) };
        if result != -1 {
            return Ok(());
        }
        let error = io::Error::last_os_error();
        if error.kind() != io::ErrorKind::Interrupted {
            return Err(error);
        }
    }
}

fn wait_readable(fd: RawFd) -> io::Result<bool> {
    let mut descriptor = PollFd {
        fd,
        events: POLLIN,
        revents: 0,
    };
    // SAFETY: descriptor points to one valid PollFd for the duration of poll
    let result = unsafe { poll(&mut descriptor, 1, WAIT_MILLISECONDS) };
    if result == -1 {
        let error = io::Error::last_os_error();
        if error.kind() == io::ErrorKind::Interrupted {
            Ok(false)
        } else {
            Err(error)
        }
    } else {
        Ok(result > 0)
    }
}

#[cfg(test)]
#[allow(unsafe_code)]
mod tests {
    use std::ffi::{c_char, c_int, c_void};
    use std::io::Write as _;
    use std::os::fd::{AsRawFd as _, FromRawFd as _};
    use std::panic::AssertUnwindSafe;
    use std::thread;
    use std::time::{Duration, Instant};

    use nagi_cli::{CancellationToken, cancellation_pair};

    use super::{ECHO, ECHONL, EchoRestore, ProcessIo, terminal_state};
    use crate::{InputMode, PromptIo, ReadResult};

    #[cfg_attr(target_os = "linux", link(name = "util"))]
    unsafe extern "C" {
        fn openpty(
            master: *mut c_int,
            slave: *mut c_int,
            name: *mut c_char,
            termios: *const c_void,
            window_size: *const c_void,
        ) -> c_int;
    }

    #[test]
    fn process_io_restores_echo_and_reads_secret_line() {
        let (master, slave) = pty();
        let original = terminal_state(slave.as_raw_fd()).expect("PTY state must be readable");
        let output = slave.try_clone().expect("PTY clone must succeed");
        let mut prompt_io = ProcessIo::new(slave, output);
        assert!(prompt_io.is_terminal());

        let mut writer_file = master.try_clone().expect("PTY clone must succeed");
        let writer = thread::spawn(move || {
            thread::sleep(Duration::from_millis(10));
            writer_file
                .write_all(b"secret\n")
                .expect("PTY write must succeed");
        });
        let result = prompt_io
            .read_line(
                &CancellationToken::new(),
                InputMode::Secret,
                crate::DEFAULT_MAX_INPUT_BYTES,
            )
            .expect("Secret read must succeed");
        writer.join().expect("writer must not panic");
        assert_eq!(result, ReadResult::Line(b"secret".to_vec()));
        assert_eq!(
            terminal_state(prompt_io.input.as_raw_fd()).expect("PTY state must be readable"),
            original
        );
    }

    #[test]
    fn echo_guard_restores_complete_state_during_unwinding() {
        let (_master, slave) = pty();
        let original = terminal_state(slave.as_raw_fd()).expect("PTY state must be readable");
        let result = std::panic::catch_unwind(AssertUnwindSafe(|| {
            let _restore = EchoRestore::disable(slave.as_raw_fd()).expect("echo must disable");
            let hidden = terminal_state(slave.as_raw_fd()).expect("PTY state must be readable");
            assert_eq!(hidden.local_flags & (ECHO | ECHONL), 0);
            panic!("exercise restoration");
        }));
        assert!(result.is_err());
        assert_eq!(
            terminal_state(slave.as_raw_fd()).expect("PTY state must be readable"),
            original
        );
    }

    #[test]
    fn process_read_observes_cancellation_without_input() {
        let (_master, slave) = pty();
        let output = slave.try_clone().expect("PTY clone must succeed");
        let mut prompt_io = ProcessIo::new(slave, output);
        let (token, handle) = cancellation_pair();
        let canceller = thread::spawn(move || {
            thread::sleep(Duration::from_millis(10));
            handle.cancel();
        });
        let started = Instant::now();
        let result = prompt_io
            .read_line(&token, InputMode::Visible, crate::DEFAULT_MAX_INPUT_BYTES)
            .expect("cancelled read must not be an I/O error");
        canceller.join().expect("canceller must not panic");
        assert_eq!(result, ReadResult::Cancelled);
        assert!(started.elapsed() < Duration::from_millis(500));
    }

    #[test]
    fn process_read_drains_an_oversized_line() {
        let (mut master, slave) = pty();
        master
            .write_all(b"abcd\nok\n")
            .expect("PTY write must succeed");
        let output = slave.try_clone().expect("PTY clone must succeed");
        let mut prompt_io = ProcessIo::new(slave, output);
        let cancellation = CancellationToken::new();
        assert_eq!(
            prompt_io
                .read_line(&cancellation, InputMode::Visible, 3)
                .expect("first read must succeed"),
            ReadResult::InputTooLong
        );
        assert_eq!(
            prompt_io
                .read_line(&cancellation, InputMode::Visible, 3)
                .expect("second read must succeed"),
            ReadResult::Line(b"ok".to_vec())
        );
        assert_eq!(
            prompt_io
                .read_line(&cancellation, InputMode::Visible, 0)
                .expect_err("zero limit must fail")
                .kind(),
            std::io::ErrorKind::InvalidInput
        );
    }

    fn pty() -> (std::fs::File, std::fs::File) {
        let mut master = -1;
        let mut slave = -1;
        // SAFETY: pointers refer to writable descriptors, optional buffers are
        // null, and successful descriptors are immediately owned by File
        let result = unsafe {
            openpty(
                &mut master,
                &mut slave,
                std::ptr::null_mut(),
                std::ptr::null(),
                std::ptr::null(),
            )
        };
        assert_eq!(
            result,
            0,
            "openpty failed: {}",
            std::io::Error::last_os_error()
        );
        // SAFETY: openpty returned two unique owned descriptors
        let master = unsafe { std::fs::File::from_raw_fd(master) };
        // SAFETY: openpty returned two unique owned descriptors
        let slave = unsafe { std::fs::File::from_raw_fd(slave) };
        (master, slave)
    }
}
