//! Generates committed Unicode tables and grapheme conformance fixtures

use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const UNICODE_VERSION: &str = "17.0.0";

fn main() {
    if let Err(error) = run() {
        eprintln!("nagi-unicode-gen: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let arguments = Arguments::parse()?;
    let data = UnicodeData::load(&arguments.data_dir)?;
    write_if_changed(&arguments.output, &data.rust_source())?;
    if let Some(path) = arguments.fixture_output {
        let fixture = grapheme_fixture(&arguments.data_dir.join("GraphemeBreakTest.txt"))?;
        write_if_changed(&path, &fixture)?;
    }
    Ok(())
}

struct Arguments {
    data_dir: PathBuf,
    output: PathBuf,
    fixture_output: Option<PathBuf>,
}

impl Arguments {
    fn parse() -> Result<Self, String> {
        let mut data_dir = None;
        let mut output = None;
        let mut fixture_output = None;
        let mut arguments = env::args_os().skip(1);
        while let Some(argument) = arguments.next() {
            let value = arguments
                .next()
                .ok_or_else(|| format!("{} requires a value", argument.to_string_lossy()))?;
            match argument.to_str() {
                Some("--data-dir") => data_dir = Some(PathBuf::from(value)),
                Some("--out") => output = Some(PathBuf::from(value)),
                Some("--fixture-out") => fixture_output = Some(PathBuf::from(value)),
                _ => return Err(format!("unknown argument {}", argument.to_string_lossy())),
            }
        }
        Ok(Self {
            data_dir: data_dir.ok_or("missing --data-dir")?,
            output: output.ok_or("missing --out")?,
            fixture_output,
        })
    }
}

struct UnicodeData {
    grapheme_break: Vec<ValueRange>,
    indic_conjunct_break: Vec<ValueRange>,
    east_asian_width: Vec<ValueRange>,
    extended_pictographic: Vec<CodePointRange>,
    emoji_presentation: Vec<CodePointRange>,
    variation_bases: Vec<u32>,
    rgi_emoji_sequences: Vec<Vec<u32>>,
}

impl UnicodeData {
    fn load(root: &Path) -> Result<Self, String> {
        let grapheme = source(root, "GraphemeBreakProperty.txt", "17.0.0")?;
        let derived = source(root, "DerivedCoreProperties.txt", "17.0.0")?;
        let east_asian = source(root, "EastAsianWidth.txt", "17.0.0")?;
        let emoji_data = source(root, "emoji-data.txt", "17.0")?;
        let emoji_sequences = source(root, "emoji-sequences.txt", "17.0")?;
        let emoji_zwj = source(root, "emoji-zwj-sequences.txt", "17.0")?;
        let emoji_variation = source(root, "emoji-variation-sequences.txt", "17.0")?;

        let grapheme_break = parse_two_field_properties(&grapheme, |property| match property {
            "CR" => Some(1),
            "LF" => Some(2),
            "Control" => Some(3),
            "Extend" => Some(4),
            "ZWJ" => Some(5),
            "Regional_Indicator" => Some(6),
            "Prepend" => Some(7),
            "SpacingMark" => Some(8),
            "L" => Some(9),
            "V" => Some(10),
            "T" => Some(11),
            "LV" => Some(12),
            "LVT" => Some(13),
            _ => None,
        })?;
        let indic_conjunct_break = parse_indic_conjunct_break(&derived)?;
        let east_asian_width =
            parse_two_field_properties(&east_asian, |property| match property {
                "A" => Some(1),
                "W" | "F" => Some(2),
                _ => None,
            })?;
        let extended_pictographic = parse_binary_property(&emoji_data, "Extended_Pictographic")?;
        let emoji_presentation = parse_binary_property(&emoji_data, "Emoji_Presentation")?;
        let variation_bases = parse_variation_bases(&emoji_variation)?;
        let mut sequences = parse_emoji_sequences(&emoji_sequences)?;
        sequences.extend(parse_emoji_sequences(&emoji_zwj)?);
        sequences.sort_unstable();
        sequences.dedup();

        Ok(Self {
            grapheme_break,
            indic_conjunct_break,
            east_asian_width,
            extended_pictographic,
            emoji_presentation,
            variation_bases,
            rgi_emoji_sequences: sequences,
        })
    }

    fn rust_source(&self) -> String {
        let mut output = String::new();
        output.push_str("// Generated by nagi-unicode-gen from Unicode 17.0.0 data\n");
        output.push_str(
            "// Unicode data is distributed under Unicode License v3; see UNICODE-LICENSE\n",
        );
        output.push_str("// DO NOT EDIT BY HAND\n\n");
        output.push_str("pub(crate) const UNICODE_VERSION: &str = \"17.0.0\";\n\n");
        write_value_ranges(&mut output, "GRAPHEME_BREAK_RANGES", &self.grapheme_break);
        write_value_ranges(
            &mut output,
            "INDIC_CONJUNCT_BREAK_RANGES",
            &self.indic_conjunct_break,
        );
        write_value_ranges(
            &mut output,
            "EAST_ASIAN_WIDTH_RANGES",
            &self.east_asian_width,
        );
        write_ranges(
            &mut output,
            "EXTENDED_PICTOGRAPHIC_RANGES",
            &self.extended_pictographic,
        );
        write_ranges(
            &mut output,
            "EMOJI_PRESENTATION_RANGES",
            &self.emoji_presentation,
        );
        output.push_str("#[rustfmt::skip]\n");
        output.push_str("pub(crate) const EMOJI_VARIATION_BASES: &[u32] = &[\n");
        for code_point in &self.variation_bases {
            let _ = writeln!(output, "    0x{code_point:X},");
        }
        output.push_str("];\n\n");
        output.push_str("#[rustfmt::skip]\n");
        output.push_str("pub(crate) const RGI_EMOJI_SEQUENCES: &[&[u32]] = &[\n");
        for sequence in &self.rgi_emoji_sequences {
            output.push_str("    &[");
            for (index, code_point) in sequence.iter().enumerate() {
                if index != 0 {
                    output.push_str(", ");
                }
                let _ = write!(output, "0x{code_point:X}");
            }
            output.push_str("],\n");
        }
        output.push_str("];\n");
        output
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct CodePointRange {
    start: u32,
    end: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ValueRange {
    start: u32,
    end: u32,
    value: u8,
}

fn source(root: &Path, name: &str, marker: &str) -> Result<String, String> {
    let path = root.join(name);
    let input = fs::read_to_string(&path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    if !input.lines().take(30).any(|line| line.contains(marker)) {
        return Err(format!("{} is not Unicode {marker} data", path.display()));
    }
    Ok(input)
}

fn data_lines(input: &str) -> impl Iterator<Item = (usize, &str)> {
    input.lines().enumerate().filter_map(|(index, line)| {
        let data = line.split('#').next().unwrap_or_default().trim();
        (!data.is_empty()).then_some((index + 1, data))
    })
}

fn parse_two_field_properties(
    input: &str,
    property_value: impl Fn(&str) -> Option<u8>,
) -> Result<Vec<ValueRange>, String> {
    let mut ranges = Vec::new();
    for (line, data) in data_lines(input) {
        let fields: Vec<_> = data.split(';').map(str::trim).collect();
        if fields.len() != 2 {
            return Err(format!("line {line}: expected two fields"));
        }
        if let Some(value) = property_value(fields[1]) {
            let range = parse_range(fields[0], line)?;
            ranges.push(ValueRange {
                start: range.start,
                end: range.end,
                value,
            });
        }
    }
    Ok(merge_value_ranges(ranges))
}

fn parse_indic_conjunct_break(input: &str) -> Result<Vec<ValueRange>, String> {
    let mut ranges = Vec::new();
    for (line, data) in data_lines(input) {
        let fields: Vec<_> = data.split(';').map(str::trim).collect();
        if fields.len() != 3 || fields[1] != "InCB" {
            continue;
        }
        let value = match fields[2] {
            "Consonant" => 1,
            "Extend" => 2,
            "Linker" => 3,
            _ => continue,
        };
        let range = parse_range(fields[0], line)?;
        ranges.push(ValueRange {
            start: range.start,
            end: range.end,
            value,
        });
    }
    Ok(merge_value_ranges(ranges))
}

fn parse_binary_property(input: &str, wanted: &str) -> Result<Vec<CodePointRange>, String> {
    let mut ranges = Vec::new();
    for (line, data) in data_lines(input) {
        let fields: Vec<_> = data.split(';').map(str::trim).collect();
        if fields.len() != 2 {
            return Err(format!("line {line}: expected two fields"));
        }
        if fields[1] == wanted {
            ranges.push(parse_range(fields[0], line)?);
        }
    }
    Ok(merge_ranges(ranges))
}

fn parse_variation_bases(input: &str) -> Result<Vec<u32>, String> {
    let mut bases = BTreeSet::new();
    for (line, data) in data_lines(input) {
        let fields: Vec<_> = data.split(';').map(str::trim).collect();
        if fields.len() < 2 {
            return Err(format!("line {line}: expected variation fields"));
        }
        let code_points = parse_code_points(fields[0], line)?;
        if code_points.len() != 2 || !matches!(code_points[1], 0xFE0E | 0xFE0F) {
            return Err(format!("line {line}: unsupported variation sequence"));
        }
        bases.insert(code_points[0]);
    }
    Ok(bases.into_iter().collect())
}

fn parse_emoji_sequences(input: &str) -> Result<Vec<Vec<u32>>, String> {
    let mut sequences = Vec::new();
    for (line, data) in data_lines(input) {
        let fields: Vec<_> = data.split(';').map(str::trim).collect();
        if fields.len() < 2 {
            return Err(format!("line {line}: expected emoji sequence fields"));
        }
        if let Some((start, end)) = fields[0].split_once("..") {
            let start = parse_scalar(start, line)?;
            let end = parse_scalar(end, line)?;
            if start > end {
                return Err(format!("line {line}: descending sequence range"));
            }
            sequences.extend((start..=end).map(|code_point| vec![code_point]));
        } else {
            sequences.push(parse_code_points(fields[0], line)?);
        }
    }
    Ok(sequences)
}

fn parse_code_points(value: &str, line: usize) -> Result<Vec<u32>, String> {
    value
        .split_whitespace()
        .map(|code_point| parse_scalar(code_point, line))
        .collect()
}

fn parse_range(value: &str, line: usize) -> Result<CodePointRange, String> {
    let (start, end) = value.split_once("..").unwrap_or((value, value));
    let start = parse_scalar(start, line)?;
    let end = parse_scalar(end, line)?;
    if start > end {
        return Err(format!("line {line}: descending code point range"));
    }
    Ok(CodePointRange { start, end })
}

fn parse_scalar(value: &str, line: usize) -> Result<u32, String> {
    let code_point = u32::from_str_radix(value.trim(), 16)
        .map_err(|error| format!("line {line}: invalid code point {value}: {error}"))?;
    char::from_u32(code_point)
        .map(u32::from)
        .ok_or_else(|| format!("line {line}: invalid Unicode scalar U+{code_point:X}"))
}

fn merge_ranges(mut ranges: Vec<CodePointRange>) -> Vec<CodePointRange> {
    ranges.sort_unstable_by_key(|range| range.start);
    let mut merged: Vec<CodePointRange> = Vec::new();
    for range in ranges {
        if let Some(previous) = merged.last_mut() {
            if range.start <= previous.end.saturating_add(1) {
                previous.end = previous.end.max(range.end);
                continue;
            }
        }
        merged.push(range);
    }
    merged
}

fn merge_value_ranges(mut ranges: Vec<ValueRange>) -> Vec<ValueRange> {
    ranges.sort_unstable_by_key(|range| range.start);
    let mut merged: Vec<ValueRange> = Vec::new();
    for range in ranges {
        if let Some(previous) = merged.last_mut() {
            if range.value == previous.value && range.start == previous.end.saturating_add(1) {
                previous.end = range.end;
                continue;
            }
        }
        merged.push(range);
    }
    merged
}

fn write_value_ranges(output: &mut String, name: &str, ranges: &[ValueRange]) {
    output.push_str("#[rustfmt::skip]\n");
    let _ = writeln!(output, "pub(crate) const {name}: &[(u32, u32, u8)] = &[");
    for range in ranges {
        let _ = writeln!(
            output,
            "    (0x{:X}, 0x{:X}, {}),",
            range.start, range.end, range.value
        );
    }
    output.push_str("];\n\n");
}

fn write_ranges(output: &mut String, name: &str, ranges: &[CodePointRange]) {
    output.push_str("#[rustfmt::skip]\n");
    let _ = writeln!(output, "pub(crate) const {name}: &[(u32, u32)] = &[");
    for range in ranges {
        let _ = writeln!(output, "    (0x{:X}, 0x{:X}),", range.start, range.end);
    }
    output.push_str("];\n\n");
}

fn grapheme_fixture(path: &Path) -> Result<String, String> {
    let input = fs::read_to_string(path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    if !input
        .lines()
        .take(30)
        .any(|line| line.contains(UNICODE_VERSION))
    {
        return Err(format!(
            "{} is not Unicode {UNICODE_VERSION} data",
            path.display()
        ));
    }

    let mut output = String::new();
    output.push_str("# Generated from Unicode 17.0.0 GraphemeBreakTest.txt\n");
    output.push_str("# Distributed under the Unicode License v3; see UNICODE-LICENSE\n");
    output.push_str("nagi-fixture-v1\ttext-grapheme-break\n");
    let mut case_number = 0_usize;
    for (line_index, line) in input.lines().enumerate() {
        let data = line.split('#').next().unwrap_or_default().trim();
        if data.is_empty() {
            continue;
        }
        case_number += 1;
        let mut text = String::new();
        let mut boundaries = Vec::new();
        let mut byte_offset = 0_usize;
        for token in data.split_whitespace() {
            match token {
                "÷" => {
                    if boundaries.last().copied() != Some(byte_offset) {
                        boundaries.push(byte_offset);
                    }
                }
                "×" => {}
                value => {
                    let scalar = parse_scalar(value, line_index + 1)?;
                    let character = char::from_u32(scalar)
                        .ok_or_else(|| format!("line {}: invalid scalar", line_index + 1))?;
                    byte_offset += character.len_utf8();
                    let _ = write!(text, "\\u{{{scalar:X}}}");
                }
            }
        }
        let boundaries = boundaries
            .iter()
            .map(usize::to_string)
            .collect::<Vec<_>>()
            .join(",");
        let _ = writeln!(
            output,
            "unicode-{case_number:04}\ttext={text}\tboundaries={boundaries}"
        );
    }
    Ok(output)
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), String> {
    if fs::read_to_string(path).is_ok_and(|existing| existing == contents) {
        return Ok(());
    }
    fs::write(path, contents)
        .map_err(|error| format!("failed to write {}: {error}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::{CodePointRange, UnicodeData, ValueRange, merge_ranges, merge_value_ranges};

    #[test]
    fn adjacent_ranges_merge_deterministically() {
        assert_eq!(
            merge_ranges(vec![
                CodePointRange { start: 3, end: 4 },
                CodePointRange { start: 1, end: 2 },
            ]),
            vec![CodePointRange { start: 1, end: 4 }]
        );
        assert_eq!(
            merge_value_ranges(vec![
                ValueRange {
                    start: 2,
                    end: 2,
                    value: 1,
                },
                ValueRange {
                    start: 1,
                    end: 1,
                    value: 1,
                },
                ValueRange {
                    start: 3,
                    end: 3,
                    value: 2,
                },
            ]),
            vec![
                ValueRange {
                    start: 1,
                    end: 2,
                    value: 1,
                },
                ValueRange {
                    start: 3,
                    end: 3,
                    value: 2,
                },
            ]
        );
    }

    #[test]
    fn generated_collections_are_stable_under_rustfmt() {
        let source = UnicodeData {
            grapheme_break: Vec::new(),
            indic_conjunct_break: Vec::new(),
            east_asian_width: Vec::new(),
            extended_pictographic: Vec::new(),
            emoji_presentation: Vec::new(),
            variation_bases: Vec::new(),
            rgi_emoji_sequences: Vec::new(),
        }
        .rust_source();

        assert_eq!(source.matches("#[rustfmt::skip]").count(), 7);
    }
}
